// Generated by scripts/gen_api_types.py from the FastAPI OpenAPI schema.
// Do not edit by hand: run `uv run python scripts/gen_api_types.py` instead.
// Excluded from lint and format in biome.jsonc for the same reason.

export interface BackendInfo {
  name: string;
  /** 'ticker' trains per series; 'universe' can pool them. */
  scope: string;
  /** False when the required library is not installed. */
  available: boolean;
  requires?: string | null;
  description: string;
}

export interface BackendListResponse {
  backends: BackendInfo[];
}

/**
 * Re-optimise on a trailing window and hold forward, charging for trades.
 * Unlike `POST /portfolio/optimize`, nothing here is fitted on the data it is
 * scored against: at each rebalance the optimizer sees only the preceding
 * `lookback` observations.
 */
export interface BacktestRequest {
  tickers: string[];
  /** Defaults to the configured start. */
  start?: string | null;
  /** Defaults to the configured end. */
  end?: string | null;
  /** Defaults to every strategy. */
  strategies?: StrategyName[] | null;
  /** Trailing observations used to estimate returns and covariance. */
  lookback?: number;
  /** Trading days between rebalances. 21 is roughly monthly. */
  rebalance_every?: number;
  /** Cost in basis points per unit of traded notional, charged on sum |dw| at each rebalance. */
  cost_bps?: number;
  risk_free_rate?: number | null;
  constraints?: ConstraintSpec;
  /** Reserved: backtest against a forecast rather than realised returns. Not yet implemented; realised returns are always used. */
  on_forecast?: ForecastBackend | null;
}

export interface BacktestResponse {
  tickers: string[];
  /** Out-of-sample days evaluated. */
  observations: number;
  lookback: number;
  rebalance_every: number;
  cost_bps: number;
  rebalance_dates: string[];
  results: BacktestStrategyResult[];
  /** Net of costs, 1.0 invested. */
  cumulative_growth: Frame;
  gross_cumulative_growth: Frame;
  /** Rows are rebalance dates, columns strategies. */
  turnover: Frame;
  warnings?: string[];
  /** MLflow run id when tracking is enabled. */
  tracking_run_id?: string | null;
}

export interface BacktestStrategyResult {
  strategy: string;
  /** Net of costs. */
  annual_return: number;
  annual_volatility: number;
  sharpe: number;
  sortino: number;
  max_drawdown: number;
  /** Before costs. */
  gross_annual_return: number;
  /** Gross annual return minus net. */
  cost_drag: number;
  /** Mean sum |dw| per rebalance. */
  avg_turnover: number;
  /** Turnover scaled to a year. */
  annual_turnover: number;
  /** Sum of all costs, as a fraction of value. */
  total_cost: number;
  rebalances: number;
}

/**
 * Convex constraints on a fully-invested portfolio.
 * Weights always sum to 1; everything here narrows the feasible set further.
 * Contradictions are reported as a 422 before any solver runs.
 * Not every strategy can honour these: risk parity, HRP and the Gerber variants
 * determine every weight from their own construction, so a request carrying extra
 * bounds comes back with a warning naming them. `GET /meta/strategies` reports
 * which strategies respect constraints.
 */
export interface ConstraintSpec {
  /** Negative permits short positions. */
  min_weight?: number;
  max_weight?: number;
  /** Cap on gross exposure, sum |w|. 1.0 forbids shorting; 1.3 is a 130/30 mandate. Only meaningful alongside a negative min_weight. */
  max_leverage?: number | null;
  /** Named group ceilings, e.g. {"tech": [["AAPL", "MSFT"], 0.4]}. */
  group_caps?: Record<string, unknown[]>;
  /** Named group floors, same shape as group_caps. */
  group_floors?: Record<string, unknown[]>;
  /** Cap on sum |w - w_previous|. Requires previous_weights. */
  max_turnover?: number | null;
  /** Current holdings, for turnover. Omitted names count as zero. */
  previous_weights?: Record<string, number>;
}

export interface CoverageResponse {
  store_root: string;
  exists: boolean;
  tickers: string[];
  total_rows: number;
  coverage: TickerCoverage[];
  /** Consecutive stored dates more than max_gap_days apart. Weekends and holidays make small gaps normal; a large one means an interrupted ingestion or a delisting. */
  gaps: Gap[];
}

/**
 * Pluggable forecasting implementations.
 * ``NAIVE`` is the random-walk baseline (tomorrow == today). It exists because a
 * price forecaster can only be judged relative to doing nothing, and it scores
 * MASE 1.0 by definition.
 * ``TORCH_LSTM`` and ``LIGHTGBM`` are the Phase 3 models: multivariate features,
 * a return target, leak-free scaling and early stopping. ``KERAS_LSTM`` is the
 * original univariate price-level model, kept so the two can be compared.
 */
export type ForecastBackend = "naive" | "keras_lstm" | "torch_lstm" | "lightgbm";

export interface ForecastRequest {
  tickers: string[];
  /** Defaults to the configured start. */
  start?: string | null;
  /** Defaults to the configured end. */
  end?: string | null;
  /** Forecasting implementation. 'lightgbm' trains the whole universe in seconds; 'torch_lstm' and 'keras_lstm' take minutes and are better submitted through POST /pipeline/runs. */
  backend?: ForecastBackend;
  /** Ignored by 'naive' and 'keras_lstm', which always model price levels. */
  target?: ForecastTarget;
  /** Train one model across the whole universe instead of one per ticker. Supported by 'torch_lstm' and 'lightgbm'; far cheaper, and lets the model use structure shared between tickers. */
  multi_series?: boolean;
  lookback_window?: number | null;
  train_split?: number | null;
  epochs?: number | null;
  batch_size?: number | null;
  /** Number of lagged returns among the features. */
  lags?: number;
  /** Seed for reproducible training. */
  seed?: number;
}

export interface ForecastResponse {
  backend: ForecastBackend;
  target: ForecastTarget;
  multi_series: boolean;
  lookback_window: number;
  train_split: number;
  /** Tickers successfully forecast. */
  tickers: string[];
  failed?: TickerError[];
  metrics: TickerForecastMetrics[];
  /** Model output, in price units. */
  predicted_prices: Frame;
  /** Realised prices over the same window. */
  actual_prices: Frame;
  /** Simple returns derived from predicted_prices. This -- not the price level -- is what the optimizers consume. */
  predicted_returns: Frame;
  actual_returns: Frame;
  /** Backend extras, e.g. LightGBM feature importances as fractions of total split gain. */
  diagnostics?: Record<string, unknown>;
}

/**
 * What the model predicts.
 * ``RETURN`` -- tomorrow's simple return, reconstructed into a price level
 * against the last observed close. This is the actual forecasting problem.
 * ``PRICE`` -- tomorrow's price level, as the original pipeline did. Predicting a
 * price from a window of prices is close to an identity mapping, which is why it
 * scores well on R^2 and MAPE while carrying almost no information. Available so
 * the difference can be demonstrated rather than asserted.
 */
export type ForecastTarget = "return" | "price";

/**
 * A 2-D labelled table in column-oriented wire format.
 * Chosen over a list of row objects because it does not repeat the column
 * names on every one of several thousand rows, and because it maps directly
 * onto both ``pandas.DataFrame`` and the ECharts/Plotly dataset format that
 * Phase 9 will consume.
 * ``data`` is row-major: ``data[i][j]`` is the value at ``index[i]`` for
 * ``columns[j]``. ``None`` encodes a missing observation.
 * Row labels are strings so that one type covers both time series (ISO-8601
 * dates, e.g. a return series) and cross-sectional tables (tickers, e.g. a
 * weights matrix).
 */
export interface Frame {
  /** Row labels: ISO-8601 dates, or tickers. */
  index: string[];
  /** Column labels (tickers or strategy names). */
  columns: string[];
  /** Row-major values. */
  data: ((number | null)[])[];
}

export interface FrontierPointOut {
  /** Annualised. */
  expected_return: number;
  /** Annualised. */
  volatility: number;
  sharpe: number;
  weights: Record<string, number>;
}

/**
 * Trace the efficient frontier for a set of returns.
 */
export interface FrontierRequest {
  returns: Frame;
  points?: number;
  risk_free_rate?: number | null;
  constraints?: ConstraintSpec;
}

export interface FrontierResponse {
  tickers: string[];
  observations: number;
  risk_free_rate: number;
  /** Ordered by expected return. */
  points: FrontierPointOut[];
  /** Index of the highest-Sharpe point. */
  tangency_index: number;
}

export interface Gap {
  ticker: string;
  gap_start: string;
  gap_end: string;
  gap_days: number;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HealthResponse {
  status?: string;
  app: string;
  version: string;
  /** Backends available in this process. */
  forecast_backends: string[];
  /** Job store actually in use: 'redis' or 'memory'. Reported so that a fallback from Redis to the in-process store is never silent. */
  job_backend: string;
}

/**
 * Download OHLCV and merge it into the Parquet store.
 */
export interface IngestRequest {
  tickers: string[];
  /** Defaults to the configured start. */
  start?: string | null;
  /** Defaults to the configured end. */
  end?: string | null;
}

export interface IngestResponse {
  tickers: string[];
  /** Rows in the store after the merge. */
  rows_written: number;
  /** Dates not previously stored. */
  rows_added: number;
  /** Dates already stored whose values the provider has changed. */
  rows_revised: number;
  revised_tickers: string[];
  /** Up to 100 examples, newest last. */
  revisions?: Revision[];
  ingested_at: string;
}

/**
 * Returned with HTTP 202 when work is handed to the queue.
 */
export interface JobAccepted {
  job_id: string;
  state: JobState;
  status_url: string;
  result_url: string;
}

/**
 * A completed job, with its result narrowed to the shapes tasks return.
 */
export interface JobResult {
  job_id: string;
  state: JobState;
  created_at: string;
  started_at?: string | null;
  finished_at?: string | null;
  progress?: number;
  /** Current step, or the failure reason. */
  message?: string | null;
  result?: PipelineResult | BacktestResponse | IngestResponse | null;
}

export type JobState = "queued" | "running" | "succeeded" | "failed" | "cancelled";

export interface JobStatus {
  job_id: string;
  state: JobState;
  created_at: string;
  started_at?: string | null;
  finished_at?: string | null;
  progress?: number;
  /** Current step, or the failure reason. */
  message?: string | null;
  /** Populated once the state is 'succeeded'. */
  result?: unknown | null;
}

/**
 * Optimize against a caller-supplied return series.
 * ``returns`` must be *returns*, not price levels. Supplying prices produces
 * covariances and expected returns that are orders of magnitude too large and
 * renders every downstream performance figure meaningless.
 */
export interface OptimizeRequest {
  returns: Frame;
  /** Defaults to every available strategy. */
  strategies?: StrategyName[] | null;
  risk_free_rate?: number | null;
  constraints?: ConstraintSpec;
}

export interface OptimizeResponse {
  tickers: string[];
  observations: number;
  risk_free_rate: number;
  /** Rows are tickers, columns are strategy names. */
  weights: Frame;
  /** Non-fatal issues, e.g. a solver that did not converge. */
  warnings?: string[];
}

export interface PerformanceRequest {
  /** Asset returns, one column per ticker. */
  returns: Frame;
  /** Rows are tickers, columns are strategy names. */
  weights: Frame;
  risk_free_rate?: number | null;
}

export interface PerformanceResponse {
  risk_free_rate: number;
  performance: StrategyPerformance[];
  /** Per-strategy portfolio return series. */
  portfolio_returns: Frame;
  /** Compounded growth of 1.0 unit invested. */
  cumulative_growth: Frame;
}

/**
 * Forecast, optimize, construct and score in one submission.
 */
export interface PipelineRequest {
  tickers: string[];
  /** Defaults to the configured start. */
  start?: string | null;
  /** Defaults to the configured end. */
  end?: string | null;
  /** Forecasting implementation. 'lightgbm' trains the whole universe in seconds; 'torch_lstm' and 'keras_lstm' take minutes and are better submitted through POST /pipeline/runs. */
  backend?: ForecastBackend;
  /** Ignored by 'naive' and 'keras_lstm', which always model price levels. */
  target?: ForecastTarget;
  /** Train one model across the whole universe instead of one per ticker. Supported by 'torch_lstm' and 'lightgbm'; far cheaper, and lets the model use structure shared between tickers. */
  multi_series?: boolean;
  lookback_window?: number | null;
  train_split?: number | null;
  epochs?: number | null;
  batch_size?: number | null;
  /** Number of lagged returns among the features. */
  lags?: number;
  /** Seed for reproducible training. */
  seed?: number;
  strategies?: StrategyName[] | null;
  risk_free_rate?: number | null;
  /** 0 selects the lowest-volatility strategy, 1 the highest. */
  risk_tolerance?: number;
  constraints?: ConstraintSpec;
}

export interface PipelineResult {
  tickers: string[];
  failed?: TickerError[];
  backend: string;
  forecast_metrics: TickerForecastMetrics[];
  weights: Frame;
  performance: StrategyPerformance[];
  cumulative_growth: Frame;
  selected_strategy: string;
  selected_weights: Record<string, number>;
  warnings?: string[];
  /** Backend extras, e.g. LightGBM feature importances. */
  diagnostics?: Record<string, unknown>;
  /** MLflow run id when tracking is enabled, so the logged parameters and metrics can be found later. */
  tracking_run_id?: string | null;
}

export interface PricesRequest {
  tickers: string[];
  /** Defaults to the configured start. */
  start?: string | null;
  /** Defaults to the configured end. */
  end?: string | null;
}

/**
 * Adjusted closing prices.
 */
export interface PricesResponse {
  start: string;
  end: string;
  /** Tickers successfully retrieved. */
  tickers: string[];
  failed?: TickerError[];
  observations: number;
  /** True when served from the in-process price cache. */
  cached: boolean;
  prices: Frame;
}

/**
 * Run a read-only SQL query against the store.
 */
export interface QueryRequest {
  /** SELECT or WITH only. The store is exposed as a view named `prices` with columns date, ticker, open, high, low, close, adj_close, volume, ingested_at. */
  sql: string;
  limit?: number;
}

export interface QueryResponse {
  columns: string[];
  rows: unknown[][];
  row_count: number;
  truncated: boolean;
}

/**
 * Simple daily returns derived from adjusted closing prices.
 */
export interface ReturnsResponse {
  start: string;
  end: string;
  /** Tickers successfully retrieved. */
  tickers: string[];
  failed?: TickerError[];
  observations: number;
  /** True when served from the in-process price cache. */
  cached: boolean;
  returns: Frame;
}

/**
 * A stored bar the provider has since restated.
 */
export interface Revision {
  ticker: string;
  date: string;
  old_adj_close: number;
  new_adj_close: number;
}

export interface StrategyInfo {
  name: StrategyName;
  /** Human-readable name for display. */
  label: string;
  /** Broad category: mean-variance, risk-based, hierarchical, robust-covariance or tail-risk. */
  family: string;
  /** Library that solves it: 'cvxpy' or 'riskfolio'. */
  solver: string;
  /** Whether weights are constrained to be non-negative. */
  long_only: boolean;
  /** False for risk-only optimizers, which ignore the return forecast. True for exactly one of the ten strategies. */
  uses_expected_returns: boolean;
  /** False where the strategy's own construction determines every weight, leaving no freedom for caller-supplied bounds; such requests return a warning. */
  respects_constraints: boolean;
  description: string;
}

export interface StrategyListResponse {
  strategies: StrategyInfo[];
}

/**
 * Optimizer outputs. The first six values match the historical CSV columns.
 */
export type StrategyName = "Markowitz_MaxSharpe" | "Markowitz_MinVar" | "RiskParity" | "GMV" | "HRP" | "Gerber_InvVar" | "HRP_CVaR" | "Gerber_HRP" | "MinCVaR" | "MinCDaR";

export interface StrategyPerformance {
  strategy: string;
  annual_return: number;
  annual_volatility: number;
  sharpe: number;
  sortino: number;
  max_drawdown: number;
}

export interface TickerCoverage {
  ticker: string;
  rows: number;
  first_date: string;
  last_date: string;
  last_ingested: string;
  /** Distinct ingestion batches contributing rows. */
  vintages: number;
}

/**
 * A single ticker that could not be processed, and why.
 */
export interface TickerError {
  ticker: string;
  reason: string;
}

/**
 * Out-of-sample forecast quality for one ticker.
 * ``rmse``/``mae``/``mape``/``r2`` are computed on price levels and are therefore
 * scale-dependent and easy to misread: R^2 is near 1.0 for any trending series,
 * and MAPE is small for any forecast close to the last observed price.
 * ``directional_accuracy`` and ``mase_vs_naive`` are the two fields that
 * actually carry signal.
 */
export interface TickerForecastMetrics {
  ticker: string;
  observations: number;
  rmse: number;
  mae: number;
  r2: number;
  mape: number;
  /** Share of the model's directional calls that were correct; 0.5 is a coin flip. Null when the model made no directional call at all, which is the case for the flat random-walk baseline. */
  directional_accuracy: number | null;
  /** Mean absolute error divided by that of a random-walk forecast. Below 1.0 beats the naive baseline; at or above 1.0 it does not. */
  mase_vs_naive: number;
  /** Retained for continuity with earlier reports: 100 * (1 - RMSE / mean price). Not a measure of forecast skill -- a random walk typically scores above 97 on it. */
  legacy_approximate_accuracy: number;
}

export interface TrackedRun {
  run_id: string;
  run_name?: string | null;
  status: string;
  started_at?: string | null;
  ended_at?: string | null;
  /** 'pipeline' or 'backtest'. */
  kind?: string | null;
  /** Code that produced the run, when in a repository. */
  git_commit?: string | null;
  /** When the underlying prices were ingested. Two runs over the same window can disagree because the provider restated history between them. */
  data_vintage?: string | null;
  params?: Record<string, string>;
  metrics?: Record<string, number>;
}

export interface TrackedRunList {
  runs: TrackedRun[];
  total: number;
}

export interface TrackingStatus {
  enabled: boolean;
  tracking_uri?: string | null;
  experiment?: string | null;
  run_count?: number | null;
  /** How to browse these runs locally. */
  ui_command?: string | null;
  /** Why tracking is unavailable, when it is. */
  detail?: string | null;
}

/**
 * Defaults a client needs in order to build a valid request.
 */
export interface UniverseResponse {
  tickers: string[];
  default_start: string;
  default_end: string;
  lookback_window: number;
  train_split: number;
  risk_free_rate: number;
  trading_days_per_year: number;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}
