"""Generate the frontend's TypeScript contract from the API's OpenAPI schema.

    uv run python scripts/gen_api_types.py

The front end must not carry a hand-maintained copy of the API's types: a
response field renamed in `app/schemas/` would then fail silently in the
browser instead of loudly at build time. This walks the schema FastAPI already
publishes and emits `frontend/src/api/schema.ts`, which is committed so that
`npm run build` needs neither Python nor a running API.

`openapi-typescript` is the usual tool for this and is deliberately not used:
its generated `components["schemas"]["Name"]` indirection is harder to read than
named interfaces, and as of 7.13 it crashes on TypeScript 7. This handles the
subset of OpenAPI that FastAPI emits for this app, and raises on anything else
rather than guessing.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "frontend" / "src" / "api" / "schema.ts"

HEADER = """// Generated by scripts/gen_api_types.py from the FastAPI OpenAPI schema.
// Do not edit by hand: run `uv run python scripts/gen_api_types.py` instead.
/* eslint-disable */
"""


def load_schema() -> dict[str, Any]:
    """Import the app and ask it for its own schema, so this never drifts."""
    code = "import json; from app.main import app; print(json.dumps(app.openapi()))"
    out = subprocess.run(
        [sys.executable, "-c", code],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=True,
        env={"SO_JOB_BACKEND": "memory", "PATH": "/usr/bin:/bin"},
    )
    return json.loads(out.stdout)


def ts_type(node: dict[str, Any], name_hint: str = "") -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in node:
        parts = [ts_type(x, name_hint) for x in node["anyOf"]]
        # FastAPI writes `X | None` as anyOf[X, null]; dedupe so unions stay short.
        seen = [p for i, p in enumerate(parts) if p not in parts[:i]]
        return " | ".join(seen)
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    kind = node.get("type")
    if kind == "array":
        inner = ts_type(node.get("items", {}), name_hint)
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if kind == "object":
        extra = node.get("additionalProperties")
        if isinstance(extra, dict) and extra:
            return f"Record<string, {ts_type(extra, name_hint)}>"
        return "Record<string, unknown>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def emit_schema(name: str, node: dict[str, Any]) -> str:
    doc = node.get("description", "").strip()
    comment = ""
    if doc:
        lines = [line.rstrip() for line in doc.splitlines() if line.strip()]
        body = "\n".join(f" * {line}" for line in lines)
        comment = f"/**\n{body}\n */\n"

    if "enum" in node:
        members = " | ".join(json.dumps(v) for v in node["enum"])
        return f"{comment}export type {name} = {members};\n"

    props: dict[str, Any] = node.get("properties", {})
    if not props:
        return f"{comment}export type {name} = {ts_type(node, name)};\n"

    required = set(node.get("required", []))
    fields = []
    for key, prop in props.items():
        field_doc = prop.get("description", "").strip().replace("*/", "*\\/")
        if field_doc:
            one_line = " ".join(field_doc.split())
            fields.append(f"  /** {one_line} */")
        optional = "" if key in required else "?"
        fields.append(f"  {key}{optional}: {ts_type(prop, name)};")
    body = "\n".join(fields)
    return f"{comment}export interface {name} {{\n{body}\n}}\n"


def main() -> int:
    schema = load_schema()
    schemas: dict[str, Any] = schema["components"]["schemas"]
    chunks = [HEADER]
    for name in sorted(schemas):
        chunks.append(emit_schema(name, schemas[name]))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(chunks))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(schemas)} types")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
